version: '3.4'

services:
  BEGIN-ALIVE:
    image: BEGIN-ALIVE
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  dev_mongodb:
    image: mongo:latest
    container_name: mongodb
    command: [--auth]
    restart: always
    volumes:
      -  ./db:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  dev_nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    restart: always
